explorer/urls.py
from django.urls import path


from .views import (
    renderFolderView,
    renderCreateFolderView,
    renderUploadFileView,
    renderDeleteFileView,
    renderRestoreFileView,
)


urlpatterns = [
    path('<folder_id>', renderFolderView, name='folder'),
    path('create-folder/<parent_id>', renderCreateFolderView, name='create-folder'),
    path('create-file/<parent_id>', renderUploadFileView, name='create-file'),
    path('delete-file/<parent_id>/<file_id>', renderDeleteFileView, name='delete-file'),
    path('restore-file/<parent_id>/<file_id>', renderRestoreFileView, name='restore-file'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('personal.urls')),
    path('folders/', include('explorer.urls')),
]


if settings.DEBUG : # if we are in development env,
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

explorer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


FILE_TYPE = (
    ('text', 'text'),
    ('html', 'html'),
    ('css', 'css'),
    ('js', 'js'),
    ('ppt', 'ppt'),
    ('pdf', 'pdf'),
)

class Folder(models.Model) :

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=True)

    name = models.CharField(max_length=255, blank=False)
    path = models.CharField(max_length=255, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self) :
        return self.name
    

class File(models.Model) :

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=True)

    name = models.CharField(max_length=255, blank=False)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE, null=True, blank=True)
    upload_time = models.DateTimeField(auto_now_add=True)
    file_type = models.CharField(max_length=255, blank=False, choices=FILE_TYPE)

    restore_folder_id = models.CharField(max_length=255, null=True)

    file = models.FileField(null=True, blank=False)

    # no need of path for a file (as it is folder path + file name)
    
    def __str__(self) :
        return self.name

explorer/forms.py
from django import forms


from .models import (
    Folder,
    File,
)


class FolderCreationForm(forms.ModelForm) :

    class Meta :
        model = Folder
        fields = ('name',)


class FileUploadForm(forms.ModelForm) :
    
    class Meta :
        model = File
        fields = ('name', 'file', 'file_type')

explorer/views.py
from django.shortcuts import render, redirect
from django.template.defaulttags import register

from .models import (
    Folder,
    File,
)

from .forms import (
    FolderCreationForm,
    FileUploadForm,
)


APPNAME = 'explorer'

# Create your views here.

# def getParentPath(current) :
#     parent = curr
#     while parent is not None :


@register.filter
def formatDateTime(upload_time) :
    return upload_time.strftime("%m/%d/%Y, %H:%M:%S")

@register.filter
def isTrashFolder(request, folder_id) :
    # print(request, folder_id, request.user.dbuser.trash_id, type(request.user.dbuser.trash_id), type(folder_id))
    return str(request.user.dbuser.trash_id) == str(folder_id)


def renderFolderView(request, folder_id) :
    if not request.user.is_authenticated :
        return redirect('login')
    
    if request.user.is_superuser :
       return redirect('home')
    
    context = {}

    try :
        folder = Folder.objects.get(id=folder_id)

        parent = folder.parent
        
        parents = []
        
        while parent is not None :
            parents.append(parent)
            parent = parent.parent

        parents.reverse()

        context['parents'] = parents
        context['folder'] = folder

        children = folder.folder_set.all()
        context['children'] = children

        files = folder.file_set.all()
        context['files'] = files
        for file in files :
            if file.file :
                print(file.upload_time.strftime("%m/%d/%Y, %H:%M:%S"))

        # get all files in the folder

        # print(type(request.user.dbuser.root_id), type(folder.id))

        return render(request, APPNAME + '/folder.html', context)

    
    except Folder.DoesNotExist :
        print("Folder does not exist")
        redirect('home')



def renderCreateFolderView(request, parent_id) :
    if not request.user.is_authenticated :
        return redirect('login')
    
    if request.user.is_superuser :
       return redirect('home')

    
    context = {}
    parent = Folder.objects.get(id=parent_id)
    context['folder'] = parent

    parents = []


    # if we use 'parent' for iterating param, it will be confusing
    # for folder view, parent is not current folder
    # while for create folder and upload file view the parent is same ad the current folder
    # so we start with parent's parent here and in upload file view
    par = parent.parent
    while par is not None :
        parents.append(par)
        par = par.parent

    parents.reverse()

    context['parents'] = parents



    if request.method == 'POST' :
        folderCreationForm = FolderCreationForm(request.POST)
        if folderCreationForm.is_valid() :

            folder = Folder.objects.create(
                user=request.user,
                name=request.POST['name'],
                path=parent.path + request.POST['name'] + '/',
                parent=parent,
            )

            print("folder created")

            print(f'parent is {parent} and folder is {folder}')

            # after creating a new folder, we need to send to page of new folder

            context['folder'] = folder
            context['parent'] = parent


            # request.session['context'] = context
            request.session['folder_id'] = context['folder'].id
            request.session['parent_id'] = context['parent'].id

            return redirect('folder', folder_id=folder.id)

            # return render(request, APPNAME + '/folder.html', context)
        
        else :
            print("form invalid")
            folderCreationForm = FolderCreationForm()
            context['folderCreationForm'] = folderCreationForm
            
        
    else :


        folderCreationForm = FolderCreationForm()
        context['folderCreationForm'] = folderCreationForm

    return render(request, APPNAME + '/create_folder.html', context)


def renderUploadFileView(request, parent_id) :
    if not request.user.is_authenticated :
        return redirect('login')
    
    if request.user.is_superuser :
       return redirect('home')
    
    context = {}
    parent = Folder.objects.get(id=parent_id)
    context['folder'] = parent

    parents = []

    par = parent.parent
    while par is not None :
        parents.append(par)
        par = par.parent

    parents.reverse()

    context['parents'] = parents


    if request.method == 'POST' :
        fileUploadForm = FileUploadForm(request.POST, request.FILES)
        if fileUploadForm.is_valid() :
            # create a file
            # store folder_id and parent_id in session
            # redirect to folder

            print(f'{request.FILES}')

            file = File.objects.create(
                user=request.user,
                name=request.POST['name'],
                file_type=request.POST['file_type'],
                folder=parent,
                file=request.FILES['file'],
            )

            # request.session['folder_id'] = context['folder'].id
            # request.session['parent_id'] = context['parent'].id

            return redirect('folder', folder_id=parent.id)
        else :
            print("invalid form")
            print(fileUploadForm.errors)
        return render(request, APPNAME + '/create_file.html', context)
    
    else :
        fileUploadForm = FileUploadForm()
        # print(fileUploadForm)
        context['fileUploadForm'] = fileUploadForm

    return render(request, APPNAME + '/create_file.html', context)


def renderDeleteFileView(request, parent_id, file_id) :
    if not request.user.is_authenticated :
        return redirect('login')
    
    if request.user.is_superuser :
       return redirect('home')
    
    context = {}

    
    try :
        # create a file in user's trash folder
        file = File.objects.get(id=file_id)

        # if current folder is trash, then we don't create a file again in trash
        if request.user.dbuser.trash_id != parent_id :

            trash = Folder.objects.get(id=request.user.dbuser.trash_id)
            new_file = File.objects.create(
                user=request.user,
                name=file.name,
                file_type=file.file_type,
                folder=trash,
                file=file.file,
                restore_folder_id=parent_id,
            )
            new_file.save()

        file.delete()

        

        return redirect('folder', folder_id=parent_id)
    
    except File.DoesNotExist :
        print("file not found")
        return redirect('home')
    
    # return render(request, APPNAME + '/delete_file.html', context)


def renderRestoreFileView(request, parent_id, file_id) :
    if not request.user.is_authenticated :
        return redirect('login')
    
    if request.user.is_superuser :
       return redirect('home')
    
    context = {}

    try :
        # create a file in user's trash folder
        file = File.objects.get(id=file_id)
        
        file.folder = Folder.objects.get(id=file.restore_folder_id)
        file.restore_folder_id = None
        file.save()

        

        return redirect('folder', folder_id=parent_id)
    
    except File.DoesNotExist :
        print("file not found")
        return redirect('home')

templates/explorer/create_file.html
{% extends 'personal/main.html' %}


{% block content %}

    <div class="path-div">
        <span class="path-slash">/</span>

        {% for parent in parents %}

            <a href="{% url 'folder' parent.id %}" class="path-link-bth">{{ parent }}</a>
            <span class="path-slash">/</span>

        {% endfor %}

        {{ folder }}
    </div>

    <div class="create-file-div">
        <h1>Create file</h1>

        <form action="" method="post" enctype="multipart/form-data" class="create-file-form"> {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="name" id="name" placeholder="Enter file name" required>
            </div>

            <div class="form-group">
                <input type="file" class="form-control" name="file" required id="id_file">
            </div>
            <div class="form-group">
                <select name="file_type" class="form-select" id="id_file_type" required>
                    <option value="" selected>Choose file type</option>
                  
                    <option value="text">text</option>
                  
                    <option value="html">html</option>
                  
                    <option value="css">css</option>
                  
                    <option value="js">js</option>
                  
                    <option value="ppt">ppt</option>
                  
                    <option value="pdf">pdf</option>
                  
                  </select>
            </div>

            <!-- {{ fileUploadForm.as_p }} -->
            <button type="submit" class="btn btn-primary">create</button>
        </form>

    </div>

{% endblock %}

templates/explorer/create_folder.html
{% extends 'personal/main.html' %}


{% block content %}

    <div class="path-div">
        <span class="path-slash">/</span>

        {% for parent in parents %}

            <a href="{% url 'folder' parent.id %}" class="path-link-bth">{{ parent }}</a>
            <span class="path-slash">/</span>

        {% endfor %}

        {{ folder }}

    </div>

    <div class="create-folder-div">
        <h1>Create folder</h1>

        <form action="" method="post" class="create-folder-form"> {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="name" id="name" placeholder="Enter folder name" required>
            </div>
            <button type="submit" class="btn btn-primary">create</button>
        </form>

    </div>

{% endblock %}

templates/explorer/delete_file.html
{% extends 'personal/main.html' %}


{% block content %}


{% endblock %}

templates/explorer/folder.html
{% extends 'personal/main.html' %}


{% block content %}

    <div class="path-div">
        <span class="path-slash">/</span>

        {% for parent in parents %}

            <a href="{% url 'folder' parent.id %}" class="path-link-bth">{{ parent }}</a>
            <span class="path-slash">/</span>

        {% endfor %}

        {{ folder }}
    </div>


    <div class="directory">
        {% for child in children %}
            <div class="directory-item folder">
                <a href="{% url 'folder' child.id %}" class="folder-link">{{ child }}</a>
                <p class="modified-time">modified at</p>
                <p class="created-time">created at</p>
            </div>
        {% endfor %}

        {% for file in files %}
            <div class="directory-item file">
                {% if file.file %}
                    <a href="{{ file.file.url }}" class="file-link" target="_blank">{{ file.name }}</a>
                {% else %}
                    <h4 class="file-name">{{ file.name }}</h4>
                {% endif %}
                <p class="file-type">{{ file.file_type }}</p>
                <p class="uploaded-time">{{ file.upload_time|formatDateTime }}</p>
                <a href="{% url 'delete-file' folder.id file.id %}" class="delete-link"><i class="fa-solid fa-trash fa-spin"></i></a>

                {% if request|isTrashFolder:folder.id %}
                    <a href="{% url 'restore-file' folder.id file.id %}" class="restore-link"><i class="fa-solid fa-rotate-right fa-spin"></i></i></a>
                {% endif %}
            </div>
        {% endfor %}
    </div>

{% endblock %}